AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: cfn-test-ecr

  Cluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: cfn-test-cluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/cfn-test-log-group

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      Family: cfn-test-task
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      RequiresCompatibilities: 
        - FARGATE
      ContainerDefinitions: 
        - Name: cfn-test-container
          Cpu: 256
          Memory: 512
          Image: !Sub ${Repository.RepositoryUri}:latest
          PortMappings: 
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: HTTP
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: ap-northeast-1
              awslogs-stream-prefix: ecs 

  Service:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref Cluster
      ServiceName: cfn-test-service
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      DeploymentController:
        Type: CODE_DEPLOY
      LoadBalancers: 
        - ContainerName: cfn-test-container
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGrop1Arn
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !Ref SGArn
          Subnets: 
            - !Ref Subnet1Arn
            - !Ref Subnet2Arn